lane :test do
  property_file_write(
    file: "example.properties",
    key: "VERSION",
    value: "2.1.0"
  )
  property_file_write(
    file: "example.properties",
    key: "VERSION_2",
    value: "3.1.0"
  )

end
